### ISSUE TITLE
Arduino LIB install path

### ISSUE THREAD

**Issue by mmprestine** [wollewald/EEPROM_SPI_WE#2]
It look like you restructured the github directory and now the Arduino LIB install path is broken.  One or the other needs fixing.

Arduino path: https://github.com/wollewald/EEPROM_SPI_WE-1.0.4.zip doesnt exist.

**Comment by wollewald** [comment]
Hi, I don't understand the issue. If you want to install the library then go to:

https://github.com/wollewald/EEPROM_SPI_WE 

Then click on the green Code Button and download the zip. 

Or: install the library directly via the board manager of the Arduino IDE (if you should use it). 

Both is working fine. I just tried.

And the lib file is not under: 
https://github.com/wollewald/EEPROM_SPI_WE-1.0.4.zip
Who says that it be at this place?

Instead it's here:
https://github.com/wollewald/EEPROM_SPI_WE/archive/refs/tags/1.0.4.zip
But again, usually you just go via the code button.
